[package]
name = "my-create3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.14"
rand = "0.8.4"
sha3 = "0.10.8"

[dev-dependencies]
pretty_assertions = "1.2"
